/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.DVD.System;

import java.sql.*;
import javax.swing.*;
//import java.io.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Ihunanyachi
 */
public class RentDVD_Frame extends javax.swing.JFrame {
    Connection conn = null;
ResultSet rs = null;
PreparedStatement pst = null;

    /**
     * Creates new form RentDVD_Frame
     */
    public RentDVD_Frame() {
        initComponents();
        conn = databaseConnection.ConnecrDb();
        
       // getCustomerEmail();
    }
    public void getDVDdetails(String id,String title,String genre,String rated,double price){
        txt_dvdID.setText(id);
        txt_dvdTitle.setText(title);
        combo_genre.setSelectedItem(genre);
        combo_rated.setSelectedItem(rated);
        dvd_price = price;
         sale_item_title = title;
         
        
    }
   /* private void getCustomerEmail(){
        String cusID = txt_customerID.getText();
        try{
           String sql = "select * from customer where ID='"+cusID+"'"; 
           pst = conn.prepareStatement(sql);
           rs = pst.executeQuery();
           if(rs.next()){
           String email = rs.getString("Email");
           customerEmail = email;
           }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            try{
                rs.close();
            pst.close();
            }catch(Exception e){
                
            }
            
        }
    }*/
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        returnDate = new com.toedter.calendar.JDateChooser();
        cmd_cancel = new javax.swing.JButton();
        cmd_rentDVD = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        combo_rated = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        txt_dvdTitle = new javax.swing.JTextField();
        combo_genre = new javax.swing.JComboBox();
        txt_dvdID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_customerName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_customerPhone = new javax.swing.JTextField();
        txt_customerSurname = new javax.swing.JTextField();
        txt_customerID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_searchCustomer = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txt_srchName = new javax.swing.JTextField();
        cmd_search = new javax.swing.JButton();
        txt_srchID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_srchSurname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rent DVD");

        jLabel12.setText("Return Date :");

        returnDate.setDateFormatString("dd-MM-yyyy");

        cmd_cancel.setText("Cancel");
        cmd_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_cancelActionPerformed(evt);
            }
        });

        cmd_rentDVD.setText("Rent");
        cmd_rentDVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_rentDVDActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DVD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(51, 51, 255)));

        combo_rated.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "    ", "G", "PG", "PG-13", "R", "NC-17", "R-18" }));
        combo_rated.setEnabled(false);

        jLabel9.setText("Title :");

        txt_dvdTitle.setEditable(false);
        txt_dvdTitle.setEnabled(false);

        combo_genre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "         ", "Action", "Adventure", "Animation", "Biography", "Comedy", "Crime", "Documentary", "Drama", "Family", "Fantasy", "Film-Noir", "Game-Show", "History", "Horror", "Music", "Musical", "Mystery", "News", "Reality-TV", "Romance", "Sci-Fi", "Sport", "Talk-Show", "Thriller", "War", "Western" }));
        combo_genre.setEnabled(false);

        txt_dvdID.setEditable(false);
        txt_dvdID.setEnabled(false);

        jLabel10.setText("Rated :");

        jLabel8.setText("ID :");

        jLabel11.setText("Genre :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(combo_rated, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel11))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_dvdID, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addComponent(combo_genre, 0, 1, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                            .addComponent(txt_dvdTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_dvdID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_dvdTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_genre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_rated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(51, 51, 255)));

        jLabel7.setText("Contact No. :");

        txt_customerName.setEditable(false);
        txt_customerName.setEnabled(false);

        jLabel4.setText("Name :");

        txt_customerPhone.setEditable(false);
        txt_customerPhone.setEnabled(false);

        txt_customerSurname.setEditable(false);
        txt_customerSurname.setEnabled(false);

        txt_customerID.setEditable(false);
        txt_customerID.setEnabled(false);

        jLabel6.setText("Customer ID :");

        jLabel5.setText("Surname :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_customerName)
                    .addComponent(txt_customerSurname)
                    .addComponent(txt_customerID)
                    .addComponent(txt_customerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_customerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_customerSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_customerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_customerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Customer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(51, 51, 255)));

        table_searchCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_searchCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_searchCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_searchCustomer);

        jLabel3.setText("Customer ID :");

        cmd_search.setText("Search");
        cmd_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_searchActionPerformed(evt);
            }
        });

        txt_srchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_srchIDActionPerformed(evt);
            }
        });

        jLabel2.setText("Surname :");

        jLabel1.setText("Name :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_srchName, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmd_search)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txt_srchSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txt_srchID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txt_srchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_srchSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_srchID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cmd_search, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(63, 63, 63)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmd_cancel)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(returnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cmd_rentDVD)
                        .addGap(102, 102, 102))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(returnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd_rentDVD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_srchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_srchIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_srchIDActionPerformed

    private void cmd_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_searchActionPerformed
         try{
           String sql = "select ID,Name,Surname,Email,DOB,Address,City,Post_Code,Phone,Gender from customer where ID=? or Name=? or Surname=?";
           pst = conn.prepareStatement(sql);
           pst.setString(1, txt_srchID.getText());
            pst.setString(2, txt_srchName.getText());
             pst.setString(3, txt_srchSurname.getText());
            rs = pst.executeQuery();
            table_searchCustomer.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
            pst.close();
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
         finally{
            try{
                rs.close();
            pst.close();
            }catch(Exception e){
                
            }
            
            
        }
    }//GEN-LAST:event_cmd_searchActionPerformed

    private void table_searchCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_searchCustomerMouseClicked
        int row = table_searchCustomer.getSelectedRow();
            String Table_click = (table_searchCustomer.getModel().getValueAt(row, 0).toString());
            
            try{
            
            String sql = "select * from customer where ID='"+Table_click+"' ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if(rs.next()){
                String add1 = rs.getString("ID");
                txt_customerID.setText(add1);
                String add2 = rs.getString("Name");
                txt_customerName.setText(add2);
                String add3 = rs.getString("Surname");
                txt_customerSurname.setText(add3);
                String add9 = rs.getString("Phone");
                txt_customerPhone.setText(add9);
                String add4 = rs.getString("Email");
                customerEmail = add4;
                rs.close();
                pst.close();
                  }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally{
            try{
                rs.close();
            pst.close();
            }catch(Exception e){
                
            }
            
        }
    }//GEN-LAST:event_table_searchCustomerMouseClicked

    private void cmd_rentDVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_rentDVDActionPerformed
         if(!txt_customerName.getText().isEmpty() && !((JTextField)returnDate.getDateEditor().getUiComponent()).getText().isEmpty()){
        Calendar cal = new GregorianCalendar();
    int month = cal.get(Calendar.MONTH);
    int year = cal.get(Calendar.YEAR);
    int day = cal.get(Calendar.DAY_OF_MONTH);
    String dated;
    dated = (String)(day+"/"+(month+1)+"/"+year);
        
        try{
           String sql = "insert into currentRentals (customer_id,customer_name,customer_surname,customer_phone,"
   + "customer_email,dvd_id,dvd_title,dvd_genre,dvd_rated,dvd_price,rented_date,return_date) values(?,?,?,?,?,?,?,?,?,?,?,?)" ;
           pst = conn.prepareStatement(sql);
           pst.setString(1, txt_customerID.getText());
           pst.setString(2, txt_customerName.getText());
           pst.setString(3, txt_customerSurname.getText());
           pst.setString(4, txt_customerPhone.getText());
           pst.setString(5, customerEmail);
           pst.setString(6, txt_dvdID.getText());
           pst.setString(7, txt_dvdTitle.getText());
           pst.setObject(8, combo_genre.getSelectedItem());
           pst.setObject(9, combo_rated.getSelectedItem());
           pst.setDouble(10, dvd_price);
           pst.setString(11, dated);
           pst.setString(12, ((JTextField)returnDate.getDateEditor().getUiComponent()).getText());
           pst.execute();
       JOptionPane.showMessageDialog(null, "DVD Rented Successfully!"); 
       rs.close();
       pst.close();
       CalculatorFrame c = new CalculatorFrame();
        c.getPrice(dvd_price);
        c.setPrice();
        dispose();
        c.setVisible(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Customer Already Rented A DVD!!!");
        }finally{
            try{
                rs.close();
            pst.close();
            }catch(Exception e){
                
            }
            
        }
        try{
            
          
            
            sale_type = "Rental";
            sale_item = "DVD";
            sale_state = "Not Returned";
            sale_amount = dvd_price;
            String query = "insert into sales(sale_type,sale_item,sale_item_title,sale_amount,sale_state) values(?,?,?,?,?)";
            pst = conn.prepareStatement(query);
            pst.setString(1, sale_type);
            pst.setString(2, sale_item);
            pst.setString(3, sale_item_title);
            pst.setDouble(4, sale_amount);
            pst.setString(5, sale_state);
            pst.execute();
            pst.close();
            rs.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        try{
            String value1 = txt_dvdID.getText();
            String value2 = "Unavailable";
          String sql = "update DVD set availability='"+value2+"'where dvd_id='"+value1+"'";
          pst = conn.prepareStatement(sql);
          pst.execute();  
          rs.close();
          pst.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            try{
                rs.close();
            pst.close();
            }catch(Exception e){
                
            }
            
        }
         }
         else{
       JOptionPane.showMessageDialog(null, "Please Select A Customer and Return Date...");
        }
    }//GEN-LAST:event_cmd_rentDVDActionPerformed

    private void cmd_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_cancelActionPerformed
        AdminMainFrame callback = new AdminMainFrame();
        callback.setVisible(true);
        dispose();
    }//GEN-LAST:event_cmd_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentDVD_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentDVD_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentDVD_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentDVD_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentDVD_Frame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_cancel;
    private javax.swing.JButton cmd_rentDVD;
    private javax.swing.JButton cmd_search;
    private javax.swing.JComboBox combo_genre;
    private javax.swing.JComboBox combo_rated;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser returnDate;
    private javax.swing.JTable table_searchCustomer;
    private javax.swing.JTextField txt_customerID;
    private javax.swing.JTextField txt_customerName;
    private javax.swing.JTextField txt_customerPhone;
    private javax.swing.JTextField txt_customerSurname;
    private javax.swing.JTextField txt_dvdID;
    private javax.swing.JTextField txt_dvdTitle;
    private javax.swing.JTextField txt_srchID;
    private javax.swing.JTextField txt_srchName;
    private javax.swing.JTextField txt_srchSurname;
    // End of variables declaration//GEN-END:variables
double dvd_price;
int sale_id = 0;
String sale_type;
String sale_item;
String sale_item_title;
double sale_amount;
String sale_state;
String customerEmail;

}
